name: Demo
options:
  bundleIdPrefix: com.shinrenpan
  deploymentTarget:
    iOS: "18.0"

targets:
  Demo:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shinrenpan.Demo
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_STRICT_CONCURRENCY: targeted
